default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  username: root
  password: password
  socket: /tmp/mysql.sock
  database: <%= Rails.application.class.module_parent_name.downcase %>_development

test:
  <<: *default
  username: root
  password: password
  socket: /tmp/mysql.sock
  database: <%= Rails.application.class.module_parent_name.downcase %>_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
